# Generated by Django 5.2.4 on 2025-10-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age_gregorian',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='age_hijri',
        ),
    ]
