# Generated by Django 5.2.4 on 2025-10-18 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_age_gregorian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref', to='contacts.contact'),
        ),
    ]
