# Generated by Django 4.1.1 on 2022-09-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_modelbase_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name_english', models.CharField(max_length=50)),
                ('name_urdu', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mujtahid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name_english', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_urdu', models.CharField(max_length=100, verbose_name='Name (Urdu)')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MujtahidRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name_english', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_urdu', models.CharField(max_length=100, verbose_name='Name (Urdu)')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('mujtahid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahid')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD')], max_length=10)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.contact', verbose_name='From')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObligationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.BooleanField()),
                ('designate_for', models.CharField(choices=[('syed', 'Only Syed'), ('non_syed', 'Only Non-Syed'), ('both', 'Both(Syed & Non-Syed)')], max_length=50)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name_english', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_urdu', models.CharField(max_length=100, verbose_name='Name (Urdu)')),
                ('description_english', models.CharField(max_length=500, verbose_name='Description (English)')),
                ('description_urdu', models.CharField(max_length=500, verbose_name='Description (Urdu)')),
                ('address_english', models.CharField(max_length=500, verbose_name='Address (English)')),
                ('address_urdu', models.CharField(max_length=500, verbose_name='Address (Urdu)')),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='logo')),
                ('website_link', models.CharField(max_length=100)),
                ('social_link', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WakalaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('income_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('liability_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sadaat_liability_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('non_sadaat_liability_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('mujtahid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahid')),
                ('mujtahid_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahidrepresentative')),
                ('obligation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.obligationtype')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fund',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='modelbase_ptr',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='fundsender',
            name='modelbase_ptr',
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modelbase',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AmountCategory',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='FundSender',
        ),
        migrations.DeleteModel(
            name='ModelBase',
        ),
        migrations.AddField(
            model_name='obligation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.obligationtype', verbose_name='Obligation Type'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
