# Generated by Django 4.1.1 on 2022-09-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_contact_mujtahid_mujtahidrepresentative_obligation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='mujtahid_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligation',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligation',
            name='receipt_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligation',
            name='received_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='obligation',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reference', to='webapp.contact'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sender', to='webapp.contact', verbose_name='From'),
        ),
    ]
