# Generated by Django 4.1.1 on 2022-09-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_obligation_mujtahid_for_obligation_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='mujtahid_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahid', verbose_name='Mujtahid'),
        ),
    ]
