# Generated by Django 4.1.1 on 2022-09-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_obligation_mujtahid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationtype',
            name='designate_for',
            field=models.CharField(choices=[('syed', 'Only Syed'), ('non_syed', 'Only Non-Syed'), ('both', 'Both(Syed & Non-Syed)'), ('none', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wakalatype',
            name='income_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Income %'),
        ),
        migrations.AlterField(
            model_name='wakalatype',
            name='liability_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Liability %'),
        ),
        migrations.AlterField(
            model_name='wakalatype',
            name='mujtahid_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahid', verbose_name='Mujtahid'),
        ),
        migrations.AlterField(
            model_name='wakalatype',
            name='mujtahid_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.mujtahidrepresentative', verbose_name='Mujtahid Representative'),
        ),
        migrations.AlterField(
            model_name='wakalatype',
            name='non_sadaat_liability_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Non-Saddat Liability %'),
        ),
        migrations.AlterField(
            model_name='wakalatype',
            name='sadaat_liability_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Saddat Liability %'),
        ),
    ]
