# Generated by Django 6.0 on 2026-01-03 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='records.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('order_no', models.CharField(blank=True, default='', max_length=50)),
                ('by_person', models.CharField(blank=True, default='', max_length=100, verbose_name='By')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='Mobile No')),
                ('marhoom', models.CharField(blank=True, default='', max_length=100, verbose_name='Marhoom')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('years', models.PositiveIntegerField(default=0)),
                ('months', models.PositiveIntegerField(default=0)),
                ('days', models.PositiveIntegerField(default=0)),
                ('rate_namaz_roza', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='@ (Rate)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Note')),
                ('years_roza', models.PositiveIntegerField(default=0, verbose_name='Years (Roza)')),
                ('months_roza', models.PositiveIntegerField(default=0, verbose_name='Months (Roza)')),
                ('days_roza', models.PositiveIntegerField(default=0, verbose_name='Days (Roza)')),
                ('rate_roza', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='@ (Rate Roza)')),
                ('notes_roza', models.TextField(blank=True, default='', verbose_name='Note (Roza)')),
                ('janwar', models.CharField(blank=True, default='', max_length=100, verbose_name='Janwar')),
                ('qty_qurbani', models.PositiveIntegerField(default=0, verbose_name='Qty')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('rate_qurbani', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='@ (Rate Qurbani)')),
                ('category', models.ForeignKey(blank=True, help_text='Select category to fill relevant details below.', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.category')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='records.record')),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
            },
        ),
        migrations.CreateModel(
            name='Marhoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marhooms', to='records.record')),
            ],
            options={
                'verbose_name': 'Marhoom',
                'verbose_name_plural': 'Marhooms',
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_to', models.CharField(blank=True, default='', max_length=100, verbose_name='Given To')),
                ('quantity_fulfillment', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('giv_date', models.DateField(blank=True, null=True, verbose_name='Giv. Date')),
                ('comp_date', models.DateField(blank=True, null=True, verbose_name='Comp. Date')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='records.record')),
            ],
            options={
                'verbose_name': 'Fulfillment',
                'verbose_name_plural': 'Fulfillments',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='records.status')),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.status'),
        ),
    ]
