# Generated by Django 5.2.4 on 2025-12-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref', to='contacts.contact'),
        ),
    ]
